### ISSUE TITLE
Bug - When clicking "too fast" on save the .conf is destroyed

### ISSUE THREAD

**Issue by ghost** [smart-mobile-software/gitstack#100]
When the server has to handle many many repositories, then its getting pretty slow, which leads to the possibility to click twice on save. If so, the .conf for the repository will get syntax errors because the content is then saved twice. 

error:
httpd.exe: Syntax error on line 486 of E:/GitStack/apache/conf/httpd.conf: Syntax error on line 31 of E:/GitStack/apache/conf/gitstack/repositories/xyz.conf: </LocationMatch>#> directive missing closing '>'
[Tue Jun 12 16:33:33 2012] [warn](OS 995)The I/O operation has been aborted because of either a thread exit or an application request. : winnt_accept: Asynchronous AcceptEx failed.
[Tue Jun 12 16:33:33 2012] [warn](OS 995)The I/O operation has been aborted because of either a thread exit or an application request. : winnt_accept: Asynchronous AcceptEx failed.
[Tue Jun 12 16:33:33 2012] [warn](OS 995)The I/O operation has been aborted because of either a thread exit or an application request. : winnt_accept: Asynchronous AcceptEx failed.
[Tue Jun 12 16:33:33 2012] [warn](OS 995)The I/O operation has been aborted because of either a thread exit or an application request. : winnt_accept: Asynchronous AcceptEx failed.
[Tue Jun 12 16:33:34 2012] [notice] Child 2988: Released the start mutex
[Tue Jun 12 16:33:35 2012] [notice] Child 2988: All worker threads have exited.
[Tue Jun 12 16:33:35 2012] [notice] Child 2988: Child process is exiting

**Comment by poiuytrez** [comment]
Which operating system are you running ? 
Which GitStack version ? 

What is the exact test scenario to reproduce the issue ?
Which save button are you talking about ?

Thank for the info. :)

**Comment by ghost** [comment]
Win 2008 R2 
Gitstack 2.0.2

I have no idea how to recreate this, and i can not risk to reproduce this on the productive machine.
I have about 20 Repositories in my gitstack installation. When i add the both users manually to a repository its working as expected. I am not sure if this behavior occurs when using the Ctrl Key to select more users from that list and click ok. Or if that happens because of i clicked too fast on save. With save button i mean the save button where i can save a repository.

**Comment by ghost** [comment]
Yes it happens when selecting more users with Ctrl in the dialog box where i can give users access to repositories. When i do that manually for each user, its working

**Comment by ghost** [comment]
How to reproduce: 
create a repository
create 3 users
go to that repository and add all 3 users with ctrl in the dialog box 
when the message appears "repo saved" (similar) then the server will crash

**Comment by poiuytrez** [comment]
Thank you

**Comment by poiuytrez** [comment]
We could not reproduce the issue.
