### ISSUE TITLE
repo user is not able to browse their repo

### ISSUE THREAD

**Issue by aksharp** [smart-mobile-software/gitstack#102]
When clicking browse repo (magnifying glass) the dialog appears that says "Please enter your git repository credentials" However after entering correct credentials, the dialog asks for credentials again and doesn't let to browse repo

**Comment by poiuytrez** [comment]
Could you provide me your GitStack version?

**Comment by aksharp** [comment]
version 2.1

**Comment by poiuytrez** [comment]
Hi,

I made the test on a clean machine, I do not have any issue. Do you get anything in the apache logs?
We have written a documentation article : http://gitstack.com/web-repository-browsing/

Do you have anything different on your installation?

**Comment by poiuytrez** [comment]
No reply. I close the issue.
