### ISSUE TITLE
Display the correct URL (HTTP, HTTPS, ...) of the Repo instead of localhost

### ISSUE THREAD

**Issue by ghost** [smart-mobile-software/gitstack#105]
would be nice to see eg. git clone http://some.ip.or.domain/gitrepo.git instead of git clone http://localhost/gitrepo.git 
so it would not be necessary to change anything and copy/paste would work 
maybe a config setting like "enter the server name" or "enter the server ip" or so...

**Comment by poiuytrez** [comment]
If the server is accessed from somewhere (for example : http://someip/gitstack/ ), the correct link will be displayed. 
( https://github.com/smart-mobile-software/gitstack/pull/97 ).

Implementing your feature means that I have to override the feature #97. What do you think?

**Comment by ghost** [comment]
Sorry dont understand this. My english is not the best. What do you
mean with override feature #97?
If this is already implemented then i will check out the latest
version (currently 2.0.2)

2012/6/26 poiuytrez
reply@reply.github.com:

**Comment by poiuytrez** [comment]
Yes, this feature has been implemented in version 2.1. If you access to the administration panel using :
http://someip/gitstack/
Clone links will be written with "someip" instead of localhost.

**Comment by ghost** [comment]
Just upgraded. Thanks for that. But it would be nice to have a field like "servername" or "serverhost" where you can define your own ip/host which should be displayed. If this field is empty, the default one can be used (the one which is used for accessing the repositories).

**Comment by poiuytrez** [comment]
Good idea. I will add it to the next version.
