### ISSUE TITLE
Security: LDAP Settings are exposed (incl. password)

### ISSUE THREAD

**Issue by nothingmn** [smart-mobile-software/gitstack#107]
1. Setup LDAP for your AD
2. In a browser that is NOT authenticated against AD or GitStack, browse to the following URL:

Actual Result:

http://SITE/rest/settings/authentication/?_=1340987088950

JSON dump of the full LDAP settings, including password.

Expected Result:
Nothing.  Why does the client need the LDAP configuration at all?

This was found by browsing to http://SITE/gitstack/settings/general/

**Comment by poiuytrez** [comment]
Thank you for the security bug report. We will fix it as soon as possible.

**Comment by poiuytrez** [comment]
Why does the client need the LDAP configuration at all?
The browser needs to retrieve the authentication info to display them in the administration panel. It is currently the best practices to retrieve them using rest.

The commit bc6eeb7519370d1584844a70ec96e2599855b93d fixes the following issues :
-http://SITE/rest/settings/authentication/ is not accessible anymore when the browser is not authenticated in the administration panel
-When authenticated, the password is not exposed anymore in the GET request on http://SITE/rest/settings/authentication/ .
