### ISSUE TITLE
UI/UX Scale for the Enterprise

### ISSUE THREAD

**Issue by nothingmn** [smart-mobile-software/gitstack#108]
We have about 80 repos, rigged up to use LDAP.  And in LDAP we have about 150 users which will need access to our repositories.

In the UI, the "Repositories" navigation path takes about 30 seconds to load, with no wait animation it may see that things are broken.  Consider loading in the list of repo's incrementally, or implement a cache on the server.

In the UI for "Manage users and groups" for each repo we have ~150 users added.  The UI handles this quite poorly and needs some serious love.

**Comment by poiuytrez** [comment]
Improvement scheduled for milestone 2.2.

**Comment by poiuytrez** [comment]
We made some tests for the "Respositories" navigation page with 80 repositories of 50 Mb each. We did not get any performance issues on Google Chrome 19 and Internet Exporer 8 (the page loads in less than a second). Which browser version do you use?

**Comment by poiuytrez** [comment]
We have just added in the add user dialog box a filter.

**Comment by poiuytrez** [comment]
"Manage users and groups" page performance improved by 95%.

**Comment by nothingmn** [comment]
I'am using Chrome.  There are two issues, that I can see.  The first is that it takes a bit of time for the server to scan the repositories folder to build its list for the client.  And then the second is the duration it takes to get that data to the client, via REST/JSON.  

Digging into the issue (using Chrome's Network tab), on the "Repositories" tab I see this call taking close to 9 seconds:

http://foo.com/rest/repository/?_=1341331689774

This call returns the list of each repository, and every user associated with each repo.  Now, if you have the same 80 repo's with the 150 users, you can imagine how large that data set will be.  ~80KB of data...  Rememer that each user is associated with each repo, so lots of data duplication here!

Any chance you could have new REST call which will just return the repository list itself, and use it on this page?  And then on the user management page, you make the request for the user information?
