### ISSUE TITLE
GIT admin console - Unable to select multiple users to repository at once - chrome

### ISSUE THREAD

**Issue by gitjulius** [smart-mobile-software/gitstack#118]
Hi,
     It does not allow to select multiple users to repository at once . Even though it says we can do it by clicking "ctrl" key.
Browser used is chrome.

-Thanks and Regards,
Julius

**Comment by poiuytrez** [comment]
Hi Julius,

Which version of GitStack are you running? Which version of Chrome? Could you try to clear your cache?

Thank you

**Comment by gitjulius** [comment]
Hi ,
  Sorry for the delay. 

git version is 1.7.11.msysgit.0  
Ghrome version is 21.0.1180.83 m

Regards,
Julius

**Comment by poiuytrez** [comment]
Hi Julius,

Which GitStack version?

**Comment by gitjulius** [comment]
As I mentioned in my previous comments its  is 1.7.11 . This  is what I  got when I executed git --version 
Do let me know if this wrong and how to do it.

**Comment by poiuytrez** [comment]
When you launch the GitStack web interface, you should see in your web browser title the GitStack version.
1.7.11 is the version of Git bundled with GitStack.

Thanks

**Comment by poiuytrez** [comment]
No reply from the user. I have to close the ticket.
