### ISSUE TITLE
When a git hook is used on repo, it slows down push

### ISSUE THREAD

**Issue by gregmoser** [smart-mobile-software/gitstack#120]
If no hook is added to the repo and i push it only takes about 1 sec.  As soon as I add some thing like pre-receive that does absolutely nothing, it takes 20 sec.  Is this a bug or is there some type of configuration i can do to speed this up.  Seems strange, but can be reproduced on multiple servers

Here is the example of a hook that takes in excess of 20sec to push once added

```
#!/bin/sh

# do nothing
```

I found this that looks similar:

http://issues.tmatesoft.com/issue/SGT-493

**Comment by poiuytrez** [comment]
Thanks Greg for the report.

**Comment by sumitverma** [comment]
Any update on this?

**Comment by poiuytrez** [comment]
I have just schedule it for the next version. We will take a look at it.

**Comment by sumitverma** [comment]
Any update on this?

**Comment by poiuytrez** [comment]
Could you try to run GitStack as a local administrator account by following this tutorial : 
http://blog.lysender.com/2009/07/run-apache-as-local-user-windows-xp/ 
?

**Comment by gregmoser** [comment]
I have tested and confirmed that following the procedures in that article resolve the issue.  Thanks for looking into this, and hopefully at some stage in the future the gitstack installer can take care of these steps for end users such as us.

**Comment by poiuytrez** [comment]
We already tried to integrate this step in the WIndows installer but it is unfortunately not possible due to windows security policy...

**Comment by gregmoser** [comment]
Sure, that makes sense.

**Comment by gregmoser** [comment]
We are running into an issue now, with database permissions and I think it is related to the workaround that we put in place.  Can you confirm or deny if this issue is related to the permission change workaround that we put in place from above?

This is the error:
http://screencast.com/t/rGIa3gvff

**Comment by poiuytrez** [comment]
Hello Greg,
Really weird. Did the error occur before?

**Comment by gregmoser** [comment]
No it just started showing up on all 3 of the servers that we have gitstack installed on.  I noticed it about 4 weeks ago, and the application still runs allowing all pushes to our repositories.  But the admin application doesn't work, it just gives that error.

**Comment by poiuytrez** [comment]
I have not heard about this kind of error before. For information, the web application try to read the file located in C:/GitStack/data/data.db file. You might need to add some more windows permissions to this file. Unfortunately we cannot reproduce the issue on our side.

**Comment by gregmoser** [comment]
That fixed it.  Looks like I just needed to give "Users" write access.

-Greg

**Comment by poiuytrez** [comment]
Good to know... I am glad that it works.
