### ISSUE TITLE
Browsing an imported repository

### ISSUE THREAD

**Issue by ledany** [smart-mobile-software/gitstack#124]
When I click on "Browse" button in an imported repository, I get the following error :

Fatal error: Call to a member function GetProject() on a non-object in D:\GitStack\gitphp\include\controller\ControllerBase.class.php on line 99.

I have installed Gitstack on 8080 port on Windows Server 2008 R2.

**Comment by poiuytrez** [comment]
Schedule to be tested tomorrow.

**Comment by poiuytrez** [comment]
We have just performed the test scenario : 
1. installed GitStack 2.2.3
2. change port to 8080
3. clone the rails project from github
4. import the rails project in GitStack
5. create and add a user to the project
6. click on the browse button

We did not get any issue during this process. Do you have some insight on what could have happen on your machine?

**Comment by poiuytrez** [comment]
No reply from the user. I have to close the ticket.

**Comment by freshlife001** [comment]
i reproduce this problem with a wrong gitphp/config/gitphp.conf file in which the install path is not right. There may be some error in the gitstack installation process.

**Comment by poiuytrez** [comment]
Could you send me the full steps that you have performed to reproduce the issue?

**Comment by freshlife001** [comment]
i am using win7 and after installation the path in the most all config files is still c:/dev/gitstack stuff.  i change those files to the right path and everything works just fine.

发自我的小米手机

poiuytrez notifications@github.com编写：

Could you send me the full steps that you have performed to reproduce the issue?

---

**Comment by freshlife001** [comment]
i also intsalled gitstack into the 'D:\GitStack\'  , so there could be an error in installation script.
