### ISSUE TITLE
Connexion failure when cloning a repository

### ISSUE THREAD

**Issue by ledany** [smart-mobile-software/gitstack#125]
I have installed Gitstack on port 8080 on my Windows Server 2008. My repository named "Core" has been created with Git and imported in Gitstack. I created the user "ledany" with rights on "Core".

For integration with Visual Studio 2010, I installed GitExtensions. I used the bash provided by this software and typed :

cd d:/testrepo

git clone http://ledany@myip:8080/Core.git

The bash answers :

Cloning into 'Core'...
error : failed connect to myip:8080; No serror while accessing http://ledany:myip:8080/Core.git/info/refs
Fatal : HTTP request failed

My password is never asked for.

**Comment by poiuytrez** [comment]
Are you able to clone the repository directory on the server? Which version of GitStack are you using?

**Comment by ledany** [comment]
No, i’m not, even on the server. I’m using 2.2.3, the last release

De : poiuytrez [mailto:notifications@github.com] 
Envoyé : jeudi 6 septembre 2012 09:33
À : smart-mobile-software/gitstack
Cc : ledany
Objet : Re: [gitstack] Connexion failure when cloning a repository (#125)

Are you able to clone the repository directory on the server? Which version of GitStack are you using?

—
Reply to this email directly or view it on GitHub https://github.com/smart-mobile-software/gitstack/issues/125#issuecomment-8324635 . 

  https://github.com/notifications/beacon/Jshd8sI44GVrKZBvymxqKMgEJgr1pL8Obj95SEQqj03uoqngk3w4Iw5CjRdYdBoZ.gif

**Comment by poiuytrez** [comment]
Could you try with the standard git distribution from [msysgit](http://code.google.com/p/msysgit/downloads/list)? 
If it stills fail, we will do some more tests on our side.

**Comment by poiuytrez** [comment]
No reply from the user. I close the ticket.
