### ISSUE TITLE
Cannot use a mapped drive for repository

### ISSUE THREAD

**Issue by draposo** [smart-mobile-software/gitstack#128]
I am installing gits stack onto a Windows server in a 2008 AD Domain.   The repositories are not local to the windows server however and mapped drives don’t  work.   How can I set git repositories to a non-local disk?   It would be nice if there was a browse function.  I would like to do something like this   \Server\Projects \ProjA\Repository \ProjB\Repository etc or worst case scenario create a mapped drive  P: to \Server\Projects and have a  repository of P:\respositories

**Comment by poiuytrez** [comment]
Duplicate issue : #114
We are already aware of it.
