### ISSUE TITLE
User cannot browse repository using the web

### ISSUE THREAD

**Issue by draposo** [smart-mobile-software/gitstack#129]
I have setup gitstack version 2.2.2 to authenticate with windows AD (2008)   The LDAP settings appear to work as I can select from my users to add to a repository access list.  However when I click on the magnifying glass I cannot browse the repository.  I am just continually asked to enter the credentials.

I was able to add users to the repository and gave them R/W permissions.    The user can login to the repository and check out the code, but the web browser does not function,

I am not sure what other logging/Info I can provide.

The following error occurs only after failing to use browse login.  I am using Google chrome as primary browser but I have also tried IE 9.

Warning: ldap_search(): Search: Bad search filter in C:\GitStack\gitphp\include\Authentication.class.php on line 275
failure: search in LDAP-tree failed
Your GitStack credentials were not entered correcly. Please ask your GitStack administrator to give you a username/password and give you access to this repository. 
Note : You have to enter the credentials of a user which has at least read access to your repository. Your GitStack administration panel username/password will not work.

**Comment by poiuytrez** [comment]
Could you send me your : 
C:/GitStack/data/settings.ini 
file?

Thank you

**Comment by draposo** [comment]
Here you go.

Thank you

Dan Raposo

---

Rite-Solutions, Inc.
88 Silva Lane
Suite 220E
Middletown, RI 02842
   p:401-847-3399 x147
   m: 401-935-7865
   f:401-847-8833

**Comment by draposo** [comment]
Sorry I thought I sent this to you yesterday.

Dan Raposo

---

Rite-Solutions, Inc.
88 Silva Lane
Suite 220E
Middletown, RI 02842
   p:401-847-3399 x147
   m: 401-935-7865
   f:401-847-8833

**Comment by draposo** [comment]
Did you get the file OK?  I think I have two threads open relating to this issue. Sorry about that.

**Comment by poiuytrez** [comment]
No problem, I have closed the other one. 

We would be glad to help you on your specific configuration issue. However, we need to book someone for your for one day adn schedule a conference call. Have you received my email on September 13th?
