### ISSUE TITLE
Error pushing local repository to server

### ISSUE THREAD

**Issue by draposo** [smart-mobile-software/gitstack#130]
recently upgraded from 2.2.2 to  2.2.3.

When I try to push my local stuff to the server I get the following error (git push  http://git.ritesolutions.com/VPT_SOURCE.git master) and nothing makes it (even worse, my local repository thinks it pushed successfully, so I can't even try to push again without remaking the repository). I tried this from both my linux and windows clients.

error: RPC failed; result=22, HTTP code = 401
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly

Since this is a third problem that may be related to permissions, perhaps there is something that I am missing on the AD side of the configuration?

**Comment by poiuytrez** [comment]
Have you received my email sent on September 13th ?

**Comment by draposo** [comment]
Any luck looking at the file and finding a configuration issue or anything? 

Thanks

**Comment by poiuytrez** [comment]
Hi Draposo,

We would be glad to help you on your specific configuration issue. However, we need to book someone for your for one day adn schedule a conference call. Have you received my email on September 13th?

**Comment by draposo** [comment]
Yes. I did receive email and I sent the settings file a couple of times.  Did you not get it? Sent from Lotus Travelerpoiuytrez --- Re: [gitstack] Error pushing local repository to server (#130) --- From:"poiuytrez" notifications@github.comTo"smart-mobile-software/gitstack" gitstack@noreply.github.comCc"draposo" draposo@rite-solutions.comDate:Tue, Sep 18, 2012 3:41 AMSubjectRe: [gitstack] Error pushing local repository to server (#130)Hi Draposo,

We would be glad to help you on your specific configuration issue. However, we need to book someone for your for one day adn schedule a conference call. Have you received my email on September 13th?

```
          —
          Reply to this email directly or view it on GitHub.
```

**Comment by poiuytrez** [comment]
I have just sent you an email about the specific technical assistance offer as your issue seems to be urgent. Could you reply to it ?

Thank you.
