### ISSUE TITLE
commitdiff hangs, ..exceeds 30 seconds..

### ISSUE THREAD

**Issue by rousseauxy** [smart-mobile-software/gitstack#131]
Was having issues with diffexe.class.php after clicking on commitdiff.
Fixed the issue by replacing gitphp (all except the config-folder) and is working smoothless now.
Only downside is the template that gitstack had is gone now aswell

**Comment by poiuytrez** [comment]
Thanks for your feedback about that. One workaround is also to run GitStack service as a local account instead of a a system account.
