### ISSUE TITLE
The service cannot start after instalation

### ISSUE THREAD

**Issue by xDEADC0DE** [smart-mobile-software/gitstack#133]
I have a windows 7 machine without collabnet svn or python. After installing gitstack the service will not start.

I have the following in the event viewer :
"httpd.exe: Syntax error on line 35 of C:/GitStack/apache/conf/httpd.conf: ServerRoot must be a valid directory"

**Comment by poiuytrez** [comment]
Could you send us your httpd.conf ?
We always test GitStack on a fresh Windows 7 & Windows Server so something must be wrong on your machine.

**Comment by xDEADC0DE** [comment]
Sure. I have tried installing gitstack multiple times, because the server had python & collabnet svn installed. Now I have removed them, but the httpd.conf seems off.

The line is "ServerRoot "C:/dev/gitstack/apache"", but I have choosen the default installation, c:/gitstack

The machine runs on Windows Server 2008

**Comment by xDEADC0DE** [comment]
Where can I send the file ?

**Comment by xDEADC0DE** [comment]
If I install gitstack in c:/dev/gitstack, the service starts but shows a 500 error.

The log says :

[Thu Sep 20 11:15:44 2012] [error] [client ::1] mod_wsgi (pid=4092): Exception occurred processing WSGI script 'C:/dev/GitStack/app/app/wsgi.py'.
[Thu Sep 20 11:15:44 2012] [error] [client ::1] Traceback (most recent call last):
[Thu Sep 20 11:15:44 2012] [error] [client ::1]   File "C:/dev/GitStack/app/app/wsgi.py", line 23, in <module>
[Thu Sep 20 11:15:44 2012] [error] [client ::1]     from django.core.wsgi import get_wsgi_application
[Thu Sep 20 11:15:44 2012] [error] [client ::1] ImportError: No module named django.core.wsgi

**Comment by poiuytrez** [comment]
I am pretty sure some stuff from collab svn and its previous python installation remains.

I recommend to:
- uninstall GitStack 
- delete your GitStack's folder
- uninstall any previous version of Python 
- (double check in your program files that a python folder or collabsvn does not exist)
- Open your environment variable :
  Select Computer from the Start menu
  Choose System Properties from the context menu
  Click Advanced system settings > Advanced tab
  Click on Environment Variables, under System Variables, find PATH, and click on it.
  Check that there is nothing related to python. If yes, delete it.
- Reinstall GitStack

**Comment by xDEADC0DE** [comment]
Thanks I will try that.

**Comment by xDEADC0DE** [comment]
There was some python left inside the PATH, thanks it works now

**Comment by poiuytrez** [comment]
That's good news.
