### ISSUE TITLE
Cannot add an allowed users when the license limit is reached

### ISSUE THREAD

**Issue by poiuytrez** [smart-mobile-software/gitstack#134]
Test scenario with a GitStack allowed for 5 users license :
1. Create 3 repos and add some users : 
repo1 : 
repo2 : user1 user2
repo3 : user3 user4 user5
1. Try to add user1 to repo1.

**Comment by poiuytrez** [comment]
On GitStack 2.2.4, when I execute the test scenario, I get a:
"can only concatenate list (not "str") to list"

**Comment by wmilward** [comment]
I was getting the same error on 2.2.4. I then downgraded to 2.0.2 and got the can't add to repositories. I then re-upgraded to GitStack 2.2.4 and now get the error that I have reached the license limit.

**Comment by poiuytrez** [comment]
We will fix the issue that we have found next week. We have no idea why you get a different error message. I will issue for you a license for 10 users freely. I am pretty sure that it will fix temporary the issue on your side.

**Comment by wmilward** [comment]
Thank you for your assistance.

Regards,

Warren Milward

**Comment by poiuytrez** [comment]
We have just sent you by email a 10 users license.

**Comment by wmilward** [comment]
Thank you very much.

**Comment by poiuytrez** [comment]
Was linked to #132.
