### ISSUE TITLE
LDAP: Everyone can pull

### ISSUE THREAD

**Issue by ManuelRauber** [smart-mobile-software/gitstack#136]
Hi,

I installed GitStack and I'm using LDAP for authentification. Pushing only works when providing the credentials, but everyone can pull from the repository. What can I do so that you need credentials for pulling and pushing?

**Comment by poiuytrez** [comment]
Could you give us your GitStack version?

**Comment by ManuelRauber** [comment]
I'm running version 2.2.4

It's working now. I didn't change anything. Maybe I just mislooked .)
