### ISSUE TITLE
LDAP: Update LDAP Bind Account

### ISSUE THREAD

**Issue by ManuelRauber** [smart-mobile-software/gitstack#137]
Hi,

I'm using GItStack 2.2.4. I added LDAP configuration, everything working fine. Later on, I decided to change the LDAP Account GitStack is using for sync. 

After changing the bindable name and syncing again, pushing didn't work. Later on, I found in c:\GitStack\apache\conf\gitstack\repositories<reponame>.conf that the "AuthLDAPBindDN" did not change.

Is this a bug?

**Comment by poiuytrez** [comment]
Yes, it's a bug :+1:

**Comment by poiuytrez** [comment]
I confirm that I can reproduce the issue. The current workaround is to modify something on the repository (modify a permission for example). The configuration file will be regenerated.
