### ISSUE TITLE
 Authorization for webview does not work

### ISSUE THREAD

**Issue by poiuytrez** [smart-mobile-software/gitstack#138]
GitStack 2.2.4

**Comment by poiuytrez** [comment]
The issue occurs when GitStack is configured for "Accept https only (most secure)". The issue is not related specifically to ldap and occurs also for local gitstack users.

**Comment by poiuytrez** [comment]
Occured only when the certificate was not valid. Gitphp was checking the certificate validity. 
Fixed in the next GitStack version. 

Workaround n°1 : Use https AND http.
Workaround n°2 : Open C:/gitstack/gitphp/include/Authentication.class.php and replace it with https://github.com/smart-mobile-software/gitstack/blob/7d2e210518fe559d1692372a66c06f7c5e28524a/gitphp/include/Authentication.class.php

**Comment by kxu1988** [comment]
Workaround n°1 : Use https AND http.
Workaround n°2 : Open C:/gitstack/gitphp/include/Authentication.class.php and replace it with....

Had done that, but no use, the problem still exists

**Comment by ghost** [comment]
Worked perfect for me! Thanks
