### ISSUE TITLE
Error when pushing local repository to remote  with ldap

### ISSUE THREAD

**Issue by poiuytrez** [smart-mobile-software/gitstack#139]

**Comment by SeanFeldman** [comment]
Steps to reproduce:
1. create repository on the server
2. cloned repository locally (using TortoiseGit) 
3. added and committed a file locally to master
4. push to master -- get an error

Error details:

git.exe push --progress  "origin" master:master
Writing objects: 100% (3/3)
Writing objects: 100% (3/3), 218 bytes, done.
Total 3 (delta 0), reused 0 (delta 0)
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
error: RPC failed; result=22, HTTP code = 401
Everything up-to-date

git did not exit cleanly (exit code 1)

GitStack version: 2.2.4

**Comment by poiuytrez** [comment]
Could you try to clone, commit and push using the command line only? Tortoisegit might be configured incorrectly.

**Comment by SeanFeldman** [comment]
same result :(

**Comment by poiuytrez** [comment]
Do you have a specific ldap config?

**Comment by SeanFeldman** [comment]
Yes, I am using ldap with GitStack.

**Comment by poiuytrez** [comment]
I meant, which type of ldap, etc. 
What makes your config different from ours and other customers?

**Comment by SeanFeldman** [comment]
LDAP: Active Directory (successfully connected and verified, can see users and assign to repository)
With all the respect, question "What makes your config different from ours and other customers?" doesn't make sense to me at all, as I only know my config and not others. If you want details, please do it via email.

**Comment by poiuytrez** [comment]
Could you send us your ldap configuration details to contact[AT]gitstack.com?

**Comment by SeanFeldman** [comment]
Email sent.
