### ISSUE TITLE
GitStack, LDAP and TeamCity: Password authentication does not work

### ISSUE THREAD

**Issue by ManuelRauber** [smart-mobile-software/gitstack#141]
I've opened an issue on TeamCity for this problem, too: http://youtrack.jetbrains.com/issue/TW-24183

To clarify: I'm running GitStack on port 35000 and TeamCity on port 36000 on the same machine. My GitStack uses LDAP to authenticate the users.

For TeamCity I've a account called "teamcity" which has read / write access on the repository I want to check out. 

On my local machine I'm using TortoiseGIT for checking out sources with this url format: http://username:password@domain.tld:35000/repository.git
This works well and it works only in this way. Omitting the password, TortoiseGit fails with "401 Authentication required".

I set up TeamCity to use a server-side checkout with password authentication. TeamCity seems to check out the sources with http://username@domain.tld:35000/repository.git and fails with 401 Auth required. 
Since Dmitry Neverov from JetBrains wrote in the issue, that it is working well with his git repository, it is maybe a misbehavior of GitStack.

**Comment by poiuytrez** [comment]
Does http://username:password@domain.tld:35000/repository.git 
work with TeamCity?

**Comment by ManuelRauber** [comment]
No, you can not provide a link like that. TeamCity automatically rewrites it to http://username@domain.tld:35000/repository.git

**Comment by poiuytrez** [comment]
Hi Manuel,

Have you solved the problem with team city?

**Comment by ManuelRauber** [comment]
Hi,

no, I'm sorry. I haven't solved it yet. It seems that the current HTTP Based Authentication is not compatible with the TeamCity Password Auth.

**Comment by ManuelRauber** [comment]
Good news on this one. I updated to current TeamCity 7.1.3 and it is working now!
It's amazing :)

**Comment by poiuytrez** [comment]
Great !!!
