### ISSUE TITLE
"The system cannot find the file specified"

### ISSUE THREAD

**Issue by emlazzarin** [smart-mobile-software/gitstack#143]
I have seen a few other posts where this issue was mentioned, but none of their solutions have fixed my problem.
1. Ensure GitStack has been fully uninstalled and the GitStack folder deleted from C:\GitStack.
2. Ensure that no other services are running on ports 80 or 443.
3. Ensure all Python references have been removed from PATH (extremely inconvenient, but I did it).
4. Install GitStack (without installing Git, as Git has already been installed.
5. Navigate to http://localhost/gitstack/
6. Enter a string with no spaces into the "Create Repository" field.

C. Error message saying "The system cannot find the file specified" appears.

---
1. Create an empty folder at C:\GitStack\repositories
2. Refresh the page.
3. The folder appears under "Repositories".
4. Click the "Import" button.

C. Huge error message prints out reiterating:

WindowsError at /rest/repository/test/ [Error 3] The system cannot find the path specified: u'C:/GitStack/repositories/test/.git\_._'

---
1. Clone an existing repository into C:\GitStack\repositories
2. Refresh the page.
3. The folder appears under "Repositories".
4. Click the "Import" button.
5. Repository imports successfully.
6. Press the magnifying glass button.

C. View the following error message:

Fatal error: Call to a member function GetProject() on a non-object in C:\GitStack\gitphp\include\controller\ControllerBase.class.php on line 99

---

I have uninstalled and re-installed several times including computer restart.

**Comment by poiuytrez** [comment]
I strongly recommend to uninstall your previous Git version without installing GitStack. 
GitStack is bundled with a slightly modified version of Git.

**Comment by WORMSS** [comment]
Then re-write your program and use the PROPER version of Git.

**Comment by thure** [comment]
This is a dealbreaker. I thought GitStack would be the best solution for us, but since it apparently only works if its own proprietary version of Git is installed I've uninstalled it.

**Comment by poiuytrez** [comment]
It is basically the mainsteam version which is used into GitStack. We just copy in addition libiconv-2.dll from git/bin to git/libexec/git-core/.
