### ISSUE TITLE
No facility to reset password

### ISSUE THREAD

**Issue by biltongza** [smart-mobile-software/gitstack#152]
I set Gitstack up on my machine a few weeks ago, put in my credentials in my IDEs on all my machines and have been going at it since. Now I'd like to log in to the webconfig but I can't remember my password, and I can find nothing that lets me reset it anywhere. I even considered bruteforcing my own passwdfile in Gitstack/data, but that's going to take far too long.

**Comment by poiuytrez** [comment]
Please follow this procedure to reset your password: 
open a command line and type:
cd c:\GitStack\app
python manage.py shell

> > > from django.contrib.auth.models import User
> > > u = User.objects.get(username__exact='admin')
> > > u.set_password('whatever')
> > > u.save()
> > > quit()

**Comment by biltongza** [comment]
That worked, thanks.
