### ISSUE TITLE
How to set up post-recieve git hook with Gitstack

### ISSUE THREAD

**Issue by ruthykatz** [smart-mobile-software/gitstack#154]
Hi,

I would like to send a notification email to all users after a commit to the master branch.
How do I do that with Gitstack?

Thanks,

Ruthy

**Comment by poiuytrez** [comment]
Just create your scripts in:
Inside your C:/GitStack/repositories/yourrepo/hooks

I recommend also to follow theses advices:
https://github.com/smart-mobile-software/gitstack/issues/120?source=cc

Best

**Comment by ruthykatz** [comment]
Hi,

Do you have an example script for SMTP configuration?

**Comment by poiuytrez** [comment]
I would recommend to checkout this link: http://stackoverflow.com/questions/552360/git-push-email-notification
