### ISSUE TITLE
 Cannot get remote repository refs.

### ISSUE THREAD

**Issue by VincentYanJk** [smart-mobile-software/gitstack#172]
When I am trying to push one project to git by Eclipse。 I got the following Error log. It seems like doesn't matter user name or  password. Could you help confirm this issue? Y Thanks a lot in advance.

Transport Error: Cannot get remote repository refs.
https://github.com/VincentYanJk/SSMProject: cannot open git-upload-pack

**Comment by VincentYanJk** [comment]
Closing. 

Adding the option insides Eclipse immediately resolves the issue. To add the option

open preferences via application menu Window => Preferences (or on OSX Eclipse => Settings).
Navigate to Team => Git => Configuration
click Add entry..., then put http.sslVerify in the key box and false in the value box.

**Comment by rayzer1969** [comment]
Nope! Doesn't work of course. It still says: "Transport Error: Cannot get remote repository refs." Trying to learn to code is nearly impossible with how fragile and scattered the coding environment is.

**Comment by firmosfirmos** [comment]
lo solucionaste?

**Comment by firmosfirmos** [comment]
Do you solved it?
