### ISSUE TITLE
Use different location for .conf created for repositories

### ISSUE THREAD

**Issue by tprochazka** [smart-mobile-software/gitstack#33]
Gitstack create new reponame.conf in the same directory like use for default main.conf and wsgi.conf. If I create new repository with name "main" it modify original main.

Second problem is that I use own Apache server 2.4.1 and for this version doesn't exists wsgi module. So I use your apache only for administration and repositories I have mapped directly to my server. But it not possible make simple Include *.conf because it will include also main.conf and wsgi.conf

**Comment by poiuytrez** [comment]
Thank you for the feedback. I have scheduled your ticket for 1.3 release.
