### ISSUE TITLE
Active Directory / LDAP authentication

### ISSUE THREAD

**Issue by enmanuelr** [smart-mobile-software/gitstack#34]
I like what you are doing, I was actually going to write something similar (a little more bare bones) myself. 

A feature that is absolutely necessary for my use, and could be useful to others is domain authentication. Please considering adding this at some point. I can't deploy this until then.

**Comment by poiuytrez** [comment]
Thank you. I schedule it for the 1.3 release.

**Comment by sebwells** [comment]
I would also really appreciate this feature.
