### ISSUE TITLE
Reduce the size of the exe files

### ISSUE THREAD

**Issue by mgholam** [smart-mobile-software/gitstack#46]
Can you reduce the size of the git exe files, it seems they are built without the use of dll files (they share the same code).

**Comment by poiuytrez** [comment]
I have tried to rename my "lib" directory. It seems to work (which does not mean that it is working for 100% of the features without any side effetcs).
You should suggest to the msysgit team to not include the lib directory ( http://msysgit.github.com/ ). Just ask the question on their Google Group.

**Comment by mgholam** [comment]
msysgit seems to be using SYMLINKs for the exe to the main GIT.exe file, I have replaced them (11mb instead of 140mb).

**Comment by poiuytrez** [comment]
What did you replace exactly ? Could you suggest it to the msysgit team and post the google group discussion link here ?

Thank you

**Comment by mgholam** [comment]
I replaced the following : ..\git\libexec\git-core\git-diff.exe -(symlink)-> ..\git.exe [mysysgit mini install does this]
