### ISSUE TITLE
Support Virtualenv

### ISSUE THREAD

**Issue by orf** [smart-mobile-software/gitstack#53]
Installing GitStack alters your PATH to point to the python interpreter bundled with GitStack. This causes issues if you already have one installed as any python scripts executed will attempt to use the GitStack one, which often causes them to fail because of missing modules.

Is it possible to make GitStack use a virtualenv or work nicely with pre-existing Python installations?

**Comment by poiuytrez** [comment]
You are right. My advice is that you should : 
1. remove GitStack's python from your path
2. copy the content of C:\GitStack\python\Lib\site-packages in your own python.

On the long term, I think the solution is to avoid a add GitStack's python in the path. I don't know if it is possible.

**Comment by poiuytrez** [comment]
We will track this conversation on the #55 issue.
