### ISSUE TITLE
Reinstall with a different installation path prevents application from working

### ISSUE THREAD

**Issue by theLogisticsGuy** [smart-mobile-software/gitstack#63]
G'day.  Just tried to install your app to a folder other than the default "C:\gitstack" and things did not go smoothly.  I have found 5 files with hard coded wrong paths which should be "c:\devtools\GitStack\".  Some of them even have "c:\devgitstack" which I assume is a throwback from your development environment.

Further information - I installed the app to the default path first.  Then uninstalled it (using the uninstaller) and tried to re-install to the custom path.

Incidentally when we gave up on the custom path tack, uninstalled again, and reinstalled to the default path the app did not work.  We tracked that down to the PYTHON_HOME and PYTHON_PATH had multiple values in it.  This may be the original problem, come to think of it, but we ran out of time and the default path was okay for the time being.

**Comment by poiuytrez** [comment]
Hello,

We have tested to install gitstack in multiple directories, there are usually no issues.
However, you issue seems to be a bit specific.
Could you confirm that the test scenario is : 
1. Install GitStack in the C:\gitstack\
2. Uninstall GitStack
3. Install GitStack in C:\devtools\GitStack\

Also, please send me all the information that you have on the system : 
-operating system
-other software installed
-gitstack version
-etc.

Thank you

**Comment by poiuytrez** [comment]
No reply. I close the ticket.

**Comment by theLogisticsGuy** [comment]
Thanks for the whole 3 days to reply before closing the issue.

I can confirm that the test scenario you prescribed is correct.
OS is Windows 7 x64
Hudson is the only other piece of software installed.
Gitstack version is 1.3.1

**Comment by poiuytrez** [comment]
I can successfully reproduce the bug on GitStack 1.3.1 and GitStack 1.4. 
We schedule it for GitStack 1.5.

Thanks for the bug report !

**Comment by theLogisticsGuy** [comment]
Glad to help.
