### ISSUE TITLE
Active Directory Distinguished Names

### ISSUE THREAD

**Issue by pjbarry** [smart-mobile-software/gitstack#65]
Within our company's AD we have all our users under a 'London Users' directory. When entering Authentication Settings if I have a Base DN in the form:
- CN=London Users, DC=CompanyLan,DC=Local

and a Bind DN of:
- CN=gittest,CN=London Users,DC=CompanyLan,DC=Local

and then test the ldap settings i'm getting an 'Invalid credentials' error.

If I then create a user in AD in the 'Users' Folder (which we don't use for any real accounts) and change the Base dn settings to be:
- CN=Users, DC=CompanyLan,DC=Local

and a Bind DN of:
- CN=gittest,CN=Users,DC=CompanyLan,DC=Local
  
  Then the ldap settings are being used correctly and I get the green success message.

Is it possible to use CNs containing spaces?

**Comment by poiuytrez** [comment]
I have made some tests, it is possible to have spaces. 
Is London Users an organizational unit ? 
Could you try to replace : 
CN=gittest,CN=London Users,DC=CompanyLan,DC=Local
by
CN=gittest,OU=London Users,DC=CompanyLan,DC=Local

?

**Comment by pjbarry** [comment]
Thanks, that sorted the problem.
