### ISSUE TITLE
Downloaded File GitStack 1.4 Norton 360 identifies risk

### ISSUE THREAD

**Issue by GITWORKSHOP** [smart-mobile-software/gitstack#66]
Environment:

Windows 7 Home Basic
Norton 360 OEM 

Norton 360 is claiming the download to contain risks and removing the downloaded file automatically.

**Comment by poiuytrez** [comment]
Could you share a screenshot of the alert on http://tinypic.com/ ?
What is your norton version ?
Are all .exe downloaded from internet a risk ? Or is it only GitStack ?

Thank you

**Comment by poiuytrez** [comment]
Base on theses info : http://community.norton.com/t5/Norton-Internet-Security-Norton/Clarification-on-WS-Reputation-1-detection/m-p/232155

Could you please complete this wizard : 
https://submit.symantec.com/false_positive/

Thank you

**Comment by GITWORKSHOP** [comment]
Not all the .exe or binary or executable files are identified as risk by Norton 360. Only this file is being removed by Norton 360. I tried downloading another .exe ... winzip.exe which was downloaded ok and I installed the same.

Before submitting false_positive I was expecting some pretty gud validation so that its not harmful as we also were hoping to install in our dev server to test.

**Comment by poiuytrez** [comment]
Don't worry it is not a virus. However, use it at your own risk :).
I think if we sign the .exe using a $500/year certificate from symatec, we can avoid the message http://www.symantec.com/verisign/code-signing/microsoft-authenticode/buy

**Comment by poiuytrez** [comment]
Did you fill the report to symatec, so I can close the ticket ?

**Comment by RealtyMogul** [comment]
I just received this today from my Norton 360:

File: c:\users\jeff\appdata\local\github\portablegit_0812189{omitted}2332a\bin\git.exe

I'm running the Github Win 7 client.

**Comment by poiuytrez** [comment]
Is you issue related to GitStack ?

**Comment by RealtyMogul** [comment]
Sorry, I don't think it is.
This thread came up in the google results for my search and I didn't investigate deep enough.

Hope I didn't inconvenience you.
