### ISSUE TITLE
Unable to use LDAP

### ISSUE THREAD

**Issue by lethil** [smart-mobile-software/gitstack#75]
I've been attempting to hook up our network's Active Directory to GitStack. Unfortunately, I keep running into "Invalid Credentials."

We don't have anything other than an "out of the box" AD forest. The only major difference is that we are 3 DC's deep (corp.noirgamestudios.com) as opposed to 2 (contoso.com).

We tried using the recommended example, but no luck. Any help would be appreciated.

protocol : ldap 
host : [IP address of Global Catalog/Domain Controller]
port: 389 
Base dn : CN=Users,DC=corp,DC=noirgamestudios,DC=com 
Attribute : sAMAccountName 
Scope : sub 
Filter : (objectClass=person) 
Bind DN : CN=gitstack,CN=Users,DC=corp,DC=noirgamestudios,DC=com 
Bind password : *****

**Comment by poiuytrez** [comment]
We will test the scenario on monday with a 3 DC's deep forest.
"Invalid Credentials" means that GitStack is able to reach the AD server, but is not able to authenticate with the user. Really weird.

**Comment by lethil** [comment]
I tried it with my admin account too and no dice either.

On Fri, May 4, 2012 at 1:42 AM, poiuytrez <
reply@reply.github.com

**Comment by poiuytrez** [comment]
Hi,

I have created today a 3 DCs deep AD server. I do not have any issue with GitStack. I am following this tutorial to setup a clean AD server : http://forevergeeks.com/how-to-install-active-directory-on-windows-2008/

<a href="http://www.hostingpics.net/viewer.php?id=257060CaptureAD1.png"><img src="http://img11.hostingpics.net/thumbs/mini_257060CaptureAD1.png" alt="Heberger image" /></a>
<a href="http://www.hostingpics.net/viewer.php?id=627654CaptureAD2.png"><img src="http://img11.hostingpics.net/thumbs/mini_627654CaptureAD2.png" alt="Heberger image" /></a>
<a href="http://www.hostingpics.net/viewer.php?id=693148CaptureAD3.png"><img src="http://img11.hostingpics.net/thumbs/mini_693148CaptureAD3.png" alt="Heberger image" /></a>

My advice is that you should use an external tool to test your active directory settings like http://www.ldapbrowser.com/
Let me know if you have any insight of the differences between our two environments.

**Comment by lethil** [comment]
What should I do next to get it to work?

On Mon, May 7, 2012 at 5:26 AM, poiuytrez <
reply@reply.github.com

**Comment by lethil** [comment]
I figured out the issue. I was using the login name, not the user's full
name.

Now that I've fixed that, I now get the following issue when I attempt to
sync using LDAP:

LDAPError at /rest/settings/authentication/ldap/sync/ (0, 'Error') Request
Method: GET Request URL:
http://localhost/rest/settings/authentication/ldap/sync/?_=1336409908284Django
Version: 1.4 Python Executable: C:\GitStack\apache\bin\httpd.exe
Python Version: 2.7.2 Python Path: ['C:\GitStack\app',
'C:\GitStack\python\lib', 'C:\GitStack\python\python27.zip',
'C:\GitStack\python\DLLs', 'C:\GitStack\python\lib\plat-win',
'C:\GitStack\python\lib\lib-tk', 'C:\GitStack\apache\bin',
'C:\GitStack\python', 'C:\GitStack\python\lib\site-packages'] Server
time: Mon, 7 May 2012 09:58:28 -0700 Installed Applications:
('django.contrib.auth', 'django.contrib.contenttypes',
'django.contrib.sessions', 'django.contrib.sites',
'django.contrib.messages', 'django.contrib.staticfiles', 'gitstack',
'rest') Installed Middleware: ('django.middleware.common.CommonMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware') Traceback: File
"C:\GitStack\python\lib\site-packages\django\core\handlers\base.py" in
get_response 111. response = callback(request, _callback_args,
*_callback_kwargs) File "C:\GitStack\app\rest\views.py" in
rest_settings_authentication_ldap_sync 568. UserLdap.sync() File
"C:\GitStack\app\gitstack\models.py" in sync 309. con =
ldap.initialize(ldap_protocol + '://' + ldap_host + ':' + ldap_port + '/')
File "C:\GitStack\python\lib\site-packages\ldap\functions.py" in initialize
92. return LDAPObject(uri,trace_level,trace_file,trace_stack_limit) File
"C:\GitStack\python\lib\site-packages\ldap\ldapobject.py" in __init__ 71.
self._l =
ldap.functions._ldap_function_call(ldap._ldap_module_lock,_ldap.initialize,uri)
File "C:\GitStack\python\lib\site-packages\ldap\functions.py" in
_ldap_function_call 64. result = func(_args,_*kwargs) Exception Type:
LDAPError at /rest/settings/authentication/ldap/sync/ Exception Value: (0,
'Error') Request information: GET: _ = u'1336409908284' POST: No POST data
FILES: No FILES data COOKIES: csrftoken =
'9AJSxlT3H4y4aJtGCfDNJKWnLal3UjVB' sessionid =
'd81e874f9d248583975f2c47cb5afe4e' META: wsgi.multiprocess = False
HTTP_REFERER = 'http://localhost/gitstack/settings/authentication/'
SERVER_SOFTWARE = 'Apache/2.2.22 (Win32) mod_ssl/2.2.22 OpenSSL/0.9.8u
mod_wsgi/3.3 Python/2.7.2 PHP/5.3.10' SCRIPT_NAME = u''
mod_wsgi.handler_script = '' SERVER_SIGNATURE = '' REQUEST_METHOD = 'GET'
PATH_INFO = u'/rest/settings/authentication/ldap/sync/' SERVER_PROTOCOL =
'HTTP/1.1' QUERY_STRING = '_=1336409908284' HTTP_USER_AGENT = 'Mozilla/5.0
(compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)' HTTP_CONNECTION
= 'Keep-Alive' HTTP_COOKIE = 'csrftoken=9AJSxlT3H4y4aJtGCfDNJKWnLal3UjVB;
sessionid=d81e874f9d248583975f2c47cb5afe4e' SERVER_NAME = 'localhost'
REMOTE_ADDR = '::1' REMOTE_USER=$REDIRECT_REMOTE_USER = ''
mod_wsgi.request_handler = 'wsgi-script' PATHEXT =
'.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC' wsgi.url_scheme =
'http' GIT_HTTP_EXPORT_ALL = '' PATH_TRANSLATED =
'C:\GitStack\app\app\wsgi.py\rest\settings\authentication\ldap\sync\'
SERVER_PORT = '80' mod_wsgi.version = mod_wsgi.input_chunked = '0'
GIT_PROJECT_ROOT = 'C:/GitStack/repositories' SERVER_ADDR = '::1'
DOCUMENT_ROOT = 'C:/GitStack/apache/htdocs' mod_wsgi.process_group = ''
COMSPEC = 'C:\Windows\system32\cmd.exe' HTTP_X_REQUESTED_WITH =
'XMLHttpRequest' SCRIPT_FILENAME = 'C:/GitStack/app/app/wsgi.py'
SERVER_ADMIN = 'admin@example.com' wsgi.input = HTTP_HOST = 'localhost'
mod_wsgi.callable_object = 'application' wsgi.multithread = True SystemRoot
= 'C:\Windows' REQUEST_URI =
'/rest/settings/authentication/ldap/sync/?_=1336409908284' HTTP_ACCEPT =
'_/_' WINDIR = 'C:\Windows' wsgi.version = GATEWAY_INTERFACE = 'CGI/1.1'
wsgi.run_once = False wsgi.errors = REMOTE_PORT = '51104'
HTTP_ACCEPT_LANGUAGE = 'en-us' mod_wsgi.application_group = '_|'
mod_wsgi.script_reloading = '1' wsgi.file_wrapper = '' CSRF_COOKIE =
'9AJSxlT3H4y4aJtGCfDNJKWnLal3UjVB' HTTP_ACCEPT_ENCODING = 'gzip, deflate'
Settings: Using settings module app.settings USE_L10N = True
USE_THOUSAND_SEPARATOR = False CSRF_COOKIE_SECURE = False LANGUAGE_CODE =
'en-us' ROOT_URLCONF = 'app.urls' MANAGERS = DEFAULT_CHARSET = 'utf-8'
STATIC_ROOT = 'C:/GitStack/app/app/staticfiles/' MESSAGE_STORAGE =
'django.contrib.messages.storage.fallback.FallbackStorage'
EMAIL_SUBJECT_PREFIX = '[Django] ' FILE_UPLOAD_PERMISSIONS = None
URL_VALIDATOR_USER_AGENT = 'Django/1.4 (https://www.djangoproject.com)'
STATICFILES_FINDERS = SESSION_COOKIE_DOMAIN = None SESSION_COOKIE_NAME =
'sessionid' ADMIN_FOR = TIME_INPUT_FORMATS = DATABASES = {'default':
{'ENGINE': 'django.db.backends.sqlite3', 'TEST_MIRROR': None, 'NAME':
'C:/GitStack/data/data.db', 'TEST_CHARSET': None, 'TIME_ZONE':
'America/Chicago', 'TEST_COLLATION': None, 'PORT': '', 'HOST': '', 'USER':
'', 'TEST_NAME': None, 'PASSWORD': u'_******************_', 'OPTIONS': {}}}
SERVER_EMAIL = 'root@localhost' FILE_UPLOAD_HANDLERS = DEFAULT_CONTENT_TYPE
= 'text/html' APPEND_SLASH = True FIRST_DAY_OF_WEEK = 0 DATABASE_ROUTERS =
[] YEAR_MONTH_FORMAT = 'F Y' STATICFILES_STORAGE =
'django.contrib.staticfiles.storage.StaticFilesStorage' CACHES =
{'default': {'LOCATION': '', 'BACKEND':
'django.core.cache.backends.locmem.LocMemCache'}} INSTALL_DIR =
'C:/GitStack' SESSION_COOKIE_PATH = '/' USE_X_FORWARDED_HOST = False
MIDDLEWARE_CLASSES = USE_I18N = True THOUSAND_SEPARATOR = ',' SECRET_KEY =
u'**_****************_' LANGUAGE_COOKIE_NAME = 'django_language'
DEFAULT_INDEX_TABLESPACE = '' TRANSACTIONS_MANAGED = False LOGGING_CONFIG =
'django.utils.log.dictConfig' SEND_BROKEN_LINK_EMAILS = False
TEMPLATE_LOADERS = WSGI_APPLICATION = None TEMPLATE_DEBUG = True
X_FRAME_OPTIONS = 'SAMEORIGIN' AUTHENTICATION_BACKENDS =
'django.contrib.auth.backends.ModelBackend' FORCE_SCRIPT_NAME = None
CACHE_BACKEND = 'locmem://' SIGNING_BACKEND =
'django.core.signing.TimestampSigner' SESSION_COOKIE_SECURE = False
CSRF_COOKIE_DOMAIN = None FILE_CHARSET = 'utf-8' DEBUG = True
SESSION_FILE_PATH = None DEFAULT_FILE_STORAGE =
'django.core.files.storage.FileSystemStorage' INSTALLED_APPS = LANGUAGES =
SETTINGS_PATH = 'C:/GitStack/data/settings.ini' COMMENTS_ALLOW_PROFANITIES
= False STATICFILES_DIRS = PREPEND_WWW = False SECURE_PROXY_SSL_HEADER =
None GIT_PATH = 'C:/GitStack/git/bin/git.exe' SESSION_COOKIE_HTTPONLY =
True DEBUG_PROPAGATE_EXCEPTIONS = False LDAP_USERS_PATH =
'C:/GitStack/data/ldapusers.json' MONTH_DAY_FORMAT = 'F j' LOGIN_URL =
'/registration/login/' SESSION_EXPIRE_AT_BROWSER_CLOSE = False TIME_FORMAT
= 'P' DATE_INPUT_FORMATS = CSRF_COOKIE_NAME = 'csrftoken'
EMAIL_HOST_PASSWORD = u'**_****************_' PASSWORD_RESET_TIMEOUT_DAYS =
u'**_****************_' CACHE_MIDDLEWARE_ALIAS = 'default'
SESSION_SAVE_EVERY_REQUEST = False ADMIN_MEDIA_PREFIX = '/static/admin/'
NUMBER_GROUPING = 0 SESSION_ENGINE = 'django.contrib.sessions.backends.db'
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure' CSRF_COOKIE_PATH = '/'
LOGIN_REDIRECT_URL = '/accounts/profile/' LOGGING = {'loggers': {'console':
{'handlers': ['console'], 'level': 'DEBUG'}, 'django.request': {'handlers':
['mail_admins'], 'propagate': True, 'level': 'ERROR'}}, 'version': 1,
'disable_existing_loggers': False, 'filters': {'require_debug_false':
{'()': 'django.utils.log.RequireDebugFalse'}}, 'handlers': {'console':
{'class': 'logging.StreamHandler', 'level': 'DEBUG'}, 'mail_admins':
{'class': 'django.utils.log.AdminEmailHandler', 'filters':
['require_debug_false'], 'level': 'ERROR'}}} IGNORABLE_404_URLS =
LOCALE_PATHS = TEMPLATE_STRING_IF_INVALID = '' LOGOUT_URL =
'/accounts/logout/' EMAIL_USE_TLS = False FIXTURE_DIRS = EMAIL_HOST =
'localhost' DATE_FORMAT = 'N j, Y' MEDIA_ROOT = ''
DEFAULT_EXCEPTION_REPORTER_FILTER =
'django.views.debug.SafeExceptionReporterFilter' ADMINS =
FORMAT_MODULE_PATH = None DEFAULT_FROM_EMAIL = 'webmaster@localhost'
MEDIA_URL = '' DATETIME_FORMAT = 'N j, Y, P' TEMPLATE_DIRS =
'C:/GitStack/templates' REPOSITORIES_PATH = 'C:/GitStack/repositories'
SITE_ID = 1 DISALLOWED_USER_AGENTS = ALLOWED_INCLUDE_ROOTS =
DECIMAL_SEPARATOR = '.' SHORT_DATE_FORMAT = 'm/d/Y' TEST_RUNNER =
'django.test.simple.DjangoTestSuiteRunner' CACHE_MIDDLEWARE_KEY_PREFIX =
u'**_****************_' TIME_ZONE = 'America/Chicago'
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440 EMAIL_BACKEND =
'django.core.mail.backends.smtp.EmailBackend' DEFAULT_TABLESPACE = ''
TEMPLATE_CONTEXT_PROCESSORS = SESSION_COOKIE_AGE = 1209600 SETTINGS_MODULE
= 'app.settings' USE_ETAGS = False LANGUAGES_BIDI = FILE_UPLOAD_TEMP_DIR =
None INTERNAL_IPS = STATIC_URL = '/static/' EMAIL_PORT = 25 USE_TZ = False
SHORT_DATETIME_FORMAT = 'm/d/Y P' PASSWORD_HASHERS =
u'**_****************_' ABSOLUTE_URL_OVERRIDES = {}
CACHE_MIDDLEWARE_SECONDS = 600 DATETIME_INPUT_FORMATS = GROUP_FILE_PATH =
'C:/GitStack/data/groupfile' EMAIL_HOST_USER = '' PROFANITIES_LIST =
u'**_*****************' You're seeing this error because you have DEBUG =
True in your Django settings file. Change that to False, and Django will
display a standard 500 page.

**Comment by poiuytrez** [comment]
You should use a user which has a only a full name without any spaces like described in the active directory tutorial to avoid unexpected behavior : http://gitstack.com/git-and-active-directory-ldap-authentication/

**Comment by lethil** [comment]
The user that I was using had no spaces and still had that big error.

Sent from my iPhone

On May 9, 2012, at 2:06 AM, poiuytrez
reply@reply.github.com
wrote:

**Comment by poiuytrez** [comment]
Could you send me a screenshot of the details of the user that you were using ? I do not really understand the issue you had.

Thank you

**Comment by poiuytrez** [comment]
No reply, I close the issue.
