### ISSUE TITLE
Authentication skipped when cloning from url without .git extension

### ISSUE THREAD

**Issue by fjeldstad** [smart-mobile-software/gitstack#78]
I have installed GitStack 1.5 from gitstack.com, set up a repo plus a user with access rights to this repo, and now I'm running into a strange issue. When cloning from the url that ends with .git, such as https://myserver/myrepo.git, I'm prompted for credentials. But if I leave out the .git extension and clone from https://myserver/myrepo, I'm able to bypass authentication altogether. Any ideas why this is happening?

(I'm currently using a http+https configuration (port 8080 for http). TeamCity is also installed on the server, but the service is not running at the moment.)

**Comment by poiuytrez** [comment]
I have just tested, I confirm that there is an issue.

**Comment by poiuytrez** [comment]
Fixed in 2.0.1

**Comment by fjeldstad** [comment]
Awesome! Any idea when the 2.0.1 will be available on gitstack.com?

11 maj 2012 kl. 17:09 skrev poiuytrez
reply@reply.github.com:

**Comment by poiuytrez** [comment]
today :)

**Comment by fjeldstad** [comment]
Ohh, nice!
