### ISSUE TITLE
Port configuration lost after upgrade/reinstall

### ISSUE THREAD

**Issue by fjeldstad** [smart-mobile-software/gitstack#82]
We had set our GitStack server to use port 8080 for http since we're running TeamCity on port 80 on the same machine. Before installing GitStack 2.0.2, we uninstalled the previous version. After reinstallation, the GitStack windows service could not be started; it turned out that there was now a port conflict between GitStack and TeamCity. 

**Our workaround:** stop TeamCity/conflicting service, start GitStack service, save the port config (which read "8080", although the port actually used was obviously 80) and finally stop/start GitStack and TeamCity/conflicting service.

Note: TeamCity was originally installed _after_ GitStack on the server.

**Comment by GitSomeMore** [comment]
I noticed the same thing upgrading to 2.1  Despite the settings.ini having port 81, the apache listen.conf was written with port 80.  Easy to work around it, though.
