### ISSUE TITLE
LDAP with user without password -> Apache will not start

### ISSUE THREAD

**Issue by Tragen** [smart-mobile-software/gitstack#86]
In the authentication tab I added a user for Bind DN
CN=User XYZ,OU=Development,OU=abc2,OU=abc,DC=subdomain,DC=comaony,DC=int
and no password. Everything is fine and I get a list of users.
But when I add some users to a repository, GitStack service stopps. When I try to restart it, Apache tells me
that a empty ldap password value is invalid.

The Apache service named  reported the following error:

> > > AuthLDAPBindPassword takes one argument, Password to use to bind to LDAP server. If not provided, will do an anonymous bind.     .

**Comment by poiuytrez** [comment]
Thanks for the bug report.
However, the current workaround seems to use a user which has a password.

**Comment by Tragen** [comment]
I know now. But you should block it else the service fails or you find a workaround for it. I have to try it it works when you completely remove AuthLDAPBindPassword.

**Comment by poiuytrez** [comment]
You are right, we will add client side validation. I schedule it for the 2.1 release.
