### ISSUE TITLE
ImportError: No module named ldap

### ISSUE THREAD

**Issue by Kogasan** [smart-mobile-software/gitstack#90]
Hi, I am trying to implement gitstack to my existing apache 2.2.22 in XAMPP 1.7.7. First I try it with revision https://github.com/smart-mobile-software/gitstack/commit/530272c8ecb1e7a0ef3b7199096190b634ebc0a2 it works. Now I am try upgrade source code of git stack but always I get server error 500.
Apache log looks like this:

[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1] mod_wsgi (pid=8056): Exception occurred processing WSGI script 'D:/XAMPP_Server/gitstack/app/app/wsgi.py'.
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1] Traceback (most recent call last):
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\core\handlers\wsgi.py", line 241, in **call**
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     response = self.get_response(request)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\core\handlers\base.py", line 179, in get_response
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\core\handlers\base.py", line 221, in handle_uncaught_exception
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     return debug.technical_500_response(request, _exc_info)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\views\debug.py", line 66, in technical_500_response
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     html = reporter.get_traceback_html()
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\views\debug.py", line 276, in get_traceback_html
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     return t.render(c)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\template\base.py", line 140, in render
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     return self._render(context)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\template\base.py", line 134, in _render
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     return self.nodelist.render(context)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\template\base.py", line 823, in render
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     bit = self.render_node(node, context)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\template\debug.py", line 74, in render_node
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     return node.render(context)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\template\debug.py", line 84, in render
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     output = self.filter_expression.resolve(context)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\template\base.py", line 599, in resolve
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     new_obj = func(obj, *arg_vals)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\template\defaultfilters.py", line 718, in date
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     return format(value, arg)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\utils\dateformat.py", line 310, in format
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     return df.format(format_string)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\utils\dateformat.py", line 33, in format
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     pieces.append(force_unicode(getattr(self, piece)()))
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\utils\dateformat.py", line 214, in r
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     return self.format('D, j M Y H:i:s O')
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\utils\dateformat.py", line 33, in format
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     pieces.append(force_unicode(getattr(self, piece)()))
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\utils\encoding.py", line 71, in force_unicode
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     s = unicode(s)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\utils\functional.py", line 121, in __unicode_cast
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     return func(_self.**args, **self.__kw)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\utils\translation\__init**.py", line 86, in ugettext
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     return _trans.ugettext(message)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\utils\translation\trans_real.py", line 278, in ugettext
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     return do_translate(message, 'ugettext')
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\utils\translation\trans_real.py", line 268, in do_translate
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     _default = translation(settings.LANGUAGE_CODE)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\utils\translation\trans_real.py", line 183, in translation
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     default_translation = _fetch(settings.LANGUAGE_CODE)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\utils\translation\trans_real.py", line 160, in _fetch
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     app = import_module(appname)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\python\lib\site-packages\django\utils\importlib.py", line 35, in import_module
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     __import__(name)
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\app\gitstack\**init**.py", line 1, in <module>
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     from gitstack.models import Repository
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\app\gitstack\models.py", line 1, in <module>
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1]     import subprocess, ConfigParser, logging, shutil, os, ctypes, stat, ldap, jsonpickle #@UnresolvedImport
[Mon May 21 00:04:43 2012] [error] [client 127.0.0.1] ImportError: No module named ldap

**Comment by Kogasan** [comment]
I install http://pypi.python.org/pypi/python-ldap/2.4.8 and now it is loging:
.
.
.
[Mon May 21 08:27:49 2012] [error] [client 127.0.0.1]   File "D:\XAMPP_Server\gitstack\app\gitstack\models.py", line 4, in <module>
[Mon May 21 08:27:49 2012] [error] [client 127.0.0.1]     from license import LicenceChecker
[Mon May 21 08:27:49 2012] [error] [client 127.0.0.1] ImportError: No module named license

**Comment by poiuytrez** [comment]
Hi,

An integration with an other apache server is not recommended (and supported) by our team. We recommend that you use our installer and follow this article : 
http://gitstack.com/gitstack-and-other-web-servers/

Regards
