### ISSUE TITLE
Installation silently fails if port 80 is already in use

### ISSUE THREAD

**Issue by sergionalin** [smart-mobile-software/gitstack#93]
If you install gitstack while port 80/443 is in use the installation process seems to complete just fine, but then when you disable the service that was running on port 80/443 (apache), start gitstack service, log into the control panel, go to "repositories", fill in a name like "test" or "whatever" and click on "Create" you keep getting the following error back:
"The system cannot find the file specified".

Uninstalling and re-installing when port 80/443 is free fixes the problem.

Suggestion: check port 80/443 during setup and popup a warning (maybe asking the user to either enter different ports or to quit the setup and free the ports).

**Comment by poiuytrez** [comment]
This feature should be added to this installer :
http://nsis.sourceforge.net/Check_open_ports

Not sure that this code snippet is still compatible with Windows 7/Server 2008 R2.

**Comment by poiuytrez** [comment]
Done.
