### ISSUE TITLE
Repository to large

### ISSUE THREAD

**Issue by Floppynator** [smart-mobile-software/gitstack#94]
i have to import a cloned git repository with size of 2.5GB. 
Seems to be GitStack has a Timeout and crash while importing. 

Workaround for this: 
Add a new Repo over GitStack and add this as remote in my local Repo an push some things is working for me.

**Comment by poiuytrez** [comment]
Add the TimOut directive in C:/GitStack/apache/conf/httpd.conf and restart GitStack.
This should be a cleaner workaround.
