### ISSUE TITLE
Certificate based logon

### ISSUE THREAD

**Issue by ghost** [smart-mobile-software/gitstack#95]
Would be nice if there would be a easy way like on github to add new users via ssh keys

**Comment by ghost** [comment]
I did not mean adding new users i meant authenticating users via ssh keys (and not user/pass) - unhappily worded

**Comment by poiuytrez** [comment]
It is unfortunately almost impossible to perform on a Windows Server...

**Comment by poiuytrez** [comment]
I close the issue with the status "won't fix". 
Feel free to repoen it if you have any ideas on how to perform it.
