### ISSUE TITLE
Bug when installing to another harddrive

### ISSUE THREAD

**Issue by ghost** [smart-mobile-software/gitstack#96]
I just installed GitStack on E: but when i change the authentication to http+https apache wont start anymore. The eventlog says it is looking at C:(!) for the certificate. The Apache service named  reported the following error: >>> SSLCertificateFile: file ‘C:/GitStack/data/certificates/server.crt’ does not exist or is empty     .

I mistakly posted first on the main page at http://gitstack.com/questions/bug-when-installing-to-another-harddrive/
maybe that can be removed

**Comment by poiuytrez** [comment]
Which version of GitStack do you have ?

**Comment by poiuytrez** [comment]
I confirm that the issue occurs on GitStack 2.0.2. 
I schedule a fix for GitStack 2.1.

A current workaround is to modify the path to the certificates in the files : 
E:\GitStack\app\gitstack\config_template\listen_template.conf
and
E:\GitStack\apache\conf\gitstack\listen.conf

**Comment by poiuytrez** [comment]
The issue is releated to #83 and is already fixed.
